language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get install -qq python${P}-pyside
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  unit2 discover -v
