language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
install:
  - sudo apt-get install python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  unit2 discover -v
