language: python
python:
  - "2.7"
env:
  - BUILD_TYPE="dev"
  - BUILD_TYPE="released"
virtualenv:
  system_site_packages: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install python-vtk python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools swig
  - if [[ $BUILD_TYPE == 'dev' ]]; then {cd ~/; git clone https://github.com/nucleic/kiwi; python kiwi/py/build.py install}; fi
install:
  - pip install cython
  - if [[ $BUILD_TYPE == 'dev' ]]; then pip install -r dev_requirements.txt; fi
  - if [[ $BUILD_TYPE == 'released' ]]; then pip install -r release_requirements.txt; fi
  - python setup.py develop
script:
  - coverage run -m unittest2 discover -v
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
